### PR TITLE
Explicitly indicate that @oleg-nenashev does not maintain the plugin anymore

### PR DESCRIPTION
**Pull request by oleg-nenashev**
I still get private emails about the plugin sometimes. I have not been using Perforce for more than 3 years && I have no environment for testing changes even if I want to resolve something. So I would like to make my role explicit.

@rpetti I'd guess it's pretty same for you. Maybe we could just mark the plugin for adoption and move on? There is a deprecation notice in public, so it seems to be reasonable. Unfortunately, P4 plugin still does not replace all available functionality.

@rpetti @reviewbybees

### CODE REVIEW

**Comment by rpetti** [comment]
@oleg-nenashev Do we need to release the plugin again in order for your status to be updated on the plugin information site? Building and releasing this thing is a PITA.

I'd be fine with marking it for adoption, but I'm worried that people might actually adopt it, rather than improving the p4 plugin.

**Comment by oleg-nenashev** [comment]
@rpetti 

> Do we need to release the plugin again in order for your status to be updated on the plugin information site?  Building and releasing this thing is a PITA.

I know, no need to do that.

> I'd be fine with marking it for adoption, but I'm worried that people might actually adopt it, rather than improving the p4 plugin.

Well, maybe. Not sure whether P4 Plugin is better in terms of quality, its JIRA track is pretty bad IMO. But yes, we could remove the plugin from update center since there is no plan to work on it. CC @daniel-beck

**Comment by oleg-nenashev** [comment]
@rpetti The plugin is marked as deprecated on Wiki, so I doubt anyone will actually take it taking the amount of technical debt inside. WDYT about depublishing though? It will prevent the plugin from further installations.

**Comment by rpetti** [comment]
@oleg-nenashev I'm fine with depublishing it. Will that just remove it from the update center, or will it be completely removed from the mirrors and wiki as well?

**Comment by oleg-nenashev** [comment]
It will stay on Wiki and within Mirrors/Artifactory.
It just won't appear in the UC

**Pull request merged**
